"""add language to posts

Revision ID: 632e4831d271
Revises: f460dca6bcaf
Create Date: 2019-12-13 23:49:16.471439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632e4831d271'
down_revision = 'f460dca6bcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
